### ISSUE TITLE
Slow to reconnect after a Redis failover

### ISSUE THREAD

**Issue by davidor** [Kuadrant/limitador#16]
In some tests that I ran together with @slopezz , we observed that Limitador was slow to reconnect after a Redis failover. The tests were using the async-redis storage implementation.

**Comment by alexsnaps** [comment]
Let's look into this as part of the perf/QA efforts. We need to have scenarios that tests for these "failures"

**Comment by maleck13** [comment]
@alexsnaps are you still hoping to address this in v1?

**Comment by alexsnaps** [comment]
I couldn't reproduce this... so closing.
