### ISSUE TITLE
Container fails to start on OpenShift (SELinux)

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/limitador#175]
After moving to UBI8 base image (#168), Limitador container fails to start on OpenShift due to SELinux restrictions regarding the UID that executes the binary (`limitador-server`).

```
Error: container create failed: time="2023-05-09T14:34:24Z" level=error msg="runc create failed: unable to start container process: exec: \"limitador-server\": executable file not found in $PATH" 
```

### Steps to reproduce

1. On a OpenShift cluster, create a typical deployment of Limitador in the `kuadrant` namespace. You may use [Limitador Operator](https://github.com/Kuadrant/limitador-operator/) or [Kuadrant](https://github.com/Kuadrant/kuadrant-operator/) for this.
2. Check the status of the pod
    ```sh
    kubectl get pods -l app=limitador -n kuadrant
    # NAME                         READY   STATUS                 RESTARTS   AGE
    # limitador-55548b99f4-pxxxd   0/1     CreateContainerError   0          12m
    ```
3. Check the events in the namespace for failures
    ```sh
    kubectl get events --field-selector='reason==Failed' -n kuadrant
    # 99m         Warning   Failed   pod/limitador-55548b99f4-nvl68   Error: container create failed: time="2023-05-09T13:01:58Z" level=error msg="runc create failed: unable to start container process: exec: \"limitador-server\": executable file not found in $PATH"
    # […]
    ```

Tested with:

| | |
|---|---|
| Limitador version | https://github.com/Kuadrant/limitador/commit/fb68c4ae5233f64081515560e1cf700f94c0bc4d |
| OpenShift (OSD) version | 4.11.39 |

### Workaround

1. Assign the `anyuid` SCC to the `default` ServiceAccount in the namespace:
    ```sh
    oc adm policy add-scc-to-user anyuid -z default -n kuadrant
    ```
2. Restart Limitador:
    ```sh
    kubectl rollout restart deployment/limitador -n kuadrant
    ```

<br/>

Ref.: https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids

**Comment by guicassolato** [comment]
A couple options I see after doing some research and running some tests:

**OPTION 1**

Change Limitador’s Dockerfile so no custom user `limitador` is created. The `limitador-server` binary, as well as all directories in the path to the binary, must be accessible by members of the `root` Linux group. This is what [kuadrant/authorino](https://github.com/kuadrant/authorino) does.

<br/>

**OPTION 2**

Assign elevated security context to the service account that runs the `limitador` container.

A few slightly different alternatives for this option: _(equivalent actions to be performed by [kuadrant/limitador-operator](https://github.com/kuadrant/limitador-operator))_

Alternative 2.1:

```sh
oc adm policy add-scc-to-user anyuid -z default -n kuadrant
kubectl rollout restart deployment/limitador -n kuadrant
```

Alternative 2.2:

```sh
kubectl create sa limitador -n kuadrant
oc adm policy add-scc-to-user anyuid -z limitador -n kuadrant
kubectl patch deployment/limitador -p '{"spec": {"template":{"spec":{"serviceAccountName":"limitador"}}}}' -n kuadrant
```

Alternative 2.3:

```sh
kubectl create sa limitador -n kuadrant
oc adm policy add-scc-to-user nonroot -z limitador -n kuadrant
kubectl patch deployment/limitador -p '{"spec": {"template":{"spec":{"securityContext":{"runAsUser":1000,"fsGroup":1000},"serviceAccountName":"limitador"}}}}' -n kuadrant
```

**Comment by gsaslis** [comment]
I also prefer the 3rd option.

**Comment by guicassolato** [comment]
**OPTION 4**

Something between [OPTION 1](https://github.com/Kuadrant/limitador/issues/175#issuecomment-1540632360) and [OPTION 3](https://github.com/Kuadrant/limitador/issues/175#issuecomment-1541802303). The home directory ("Limitador files") is owned by `limitador:root`. While the user has full permission over the directory, group member can only `r-x`.

This should be enough to ensure safe defaults within the container for general case as well as to cover OpenShift specific case where the unprivileged user who runs the container is member of the `root` Linux group, without having to set any special pod security context.

<br/>

Thanks @eguzki and @alexsnaps

**Comment by pehala** [comment]
Tested with OpenShift 4.12, everything works as expected
