### ISSUE TITLE
Trying out Infinispan as redis service

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/limitador#185]
From https://infinispan.org/docs/stable/titles/resp/resp-endpoint.html

```
Infinispan Server includes an experimental module that implements the [RESP3 protocol](https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md). The RESP endpoint allows Redis clients to connect to one or several Infinispan-backed RESP servers and perform cache operations.
```

The main objective is to assess infinispan compatibility configured as redis backend of limitador. Performance benchmarking would also be interesting to know.

**Comment by adam-cattermole** [comment]
I've managed to get Limitador to connect to the Infinispan RESP endpoint, however the current implementation of limitador relies on several RESP commands which are not yet [supported by infinispan](https://infinispan.org/docs/stable/titles/resp/resp-endpoint.html#redis-commands_resp-endpoint).

* [`INCRBY`](https://redis.io/commands/incrby/)
* [`SADD`](https://redis.io/commands/sadd/)
* [`PTTL`](https://redis.io/commands/pttl/)

These are used [in the calls to Redis](https://github.com/Kuadrant/limitador/blob/main/limitador/src/storage/redis/scripts.rs#L15-L33) so to get this to function we'd have to rewrite it without them (or wait and see if they become supported by infinispan).

**Comment by alexsnaps** [comment]
I am going to close this as "won't fix". Two out of these 3 unsupported functions are actually core to how we do things with Redis today. I don't see any reasons to change this. Even less so to support Infinispan, so unless they add support for these functions, we probably have to keep on relying on the experimental support for Infinispan as it is currently built.
