### ISSUE TITLE
Spec Azure, Google, Redis Labs' offering (x-AZ/Region, Lua support/pipeline support, sharded?)

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/limitador#264]
Azure, Google and Redis Labs all provide other "Redis API/Protocol" compatible solution that may somewhat cover some of the usecases described in Kuadrant/architecture#62

We need a matrix that document support for these usecases, as well as support for:
 - server-side Lua scripts
 - Pipelining
 - What sharding strategy they support

**Comment by eguzki** [comment]
### WIP

| Capability / Feature  | [Elasticache for Redis](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug) | [Azure Cache for Redis](https://azure.microsoft.com/en-us/products/cache) | [Google Memorystore for Redis](https://cloud.google.com/memorystore) | [Redis Enterprise](https://redis.com/redis-enterprise-software/overview/) |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Sharding strategy  |  TODO  |  TODO  | TODO  |  TODO  |

**Comment by eguzki** [comment]
While elasticache seems to be a system implementing "Redis API", Azure cache looks like deploys instances of open source redis or redis enterprise in premium/enterprise plans. The configuration options and portfolio of features can me mapped one to one with the open source and enterprise redis.

**Comment by alexsnaps** [comment]
@eguzki anything pending here, or do we feel we can close this Issue?

**Comment by eguzki** [comment]
I think we can close this. In 6 months the offering can change. WE can have this report as base line to compare.
