### ISSUE TITLE
Counters sharable across threads

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/limitador#69]
Currently counters used in memory are non thread safe and rely on the coarse lock at the "root" level of the store. 
I don't think we need this to be the case. It'd require a few other changes, but introducing a a new counter would be step one in providing more parallelism to Limitador.

### Non Blocking Counter using Atomic operations on u64.

I think we can build a counter that increments a `AtomicU64`, and uses an expiry date as the "marker" for what thread gets to reset the counter (e.g. CASing the new expiry in place) when its expired.

Some example implementation of this:

<details>

```rust

const ORDERING: Ordering = Ordering::SeqCst; // This might be overly conservative

pub struct NonBlockingCounter {
    value: AtomicU64,
    expires_at: AtomicU64,
    duration: u64,
}

impl NonBlockingCounter {

    // moved the notion of clock outside, the limit can hold that logic, or we add a `next(&self) -> u64`
    pub fn next_at(&self, at: u64) -> u64 {
        let expiry = self.expires_at.load(ORDERING);
        if at >= expiry {
            // counter expired, resetting
            if self.expires_at.compare_exchange(expiry, at + self.duration, ORDERING, ORDERING).is_ok() {
                // we won resetting the expiry, so now resetting actual counter
                self.value.store(1, ORDERING);
                // return 1 as the new value right away
                return 1;
            }
            // if on the other hand we lost the race resetting the expiry, we just go on to read the counter as if it didn't expire
        }
        // store and return the incremented value
        let previous = self.value.fetch_add(1, ORDERING);
        if previous == u64::MAX {
            // we're rolling over!
        }
        previous + 1
    }
}

```

Notes on my quick thinking about `Ordering`: `expiry_at` accesses should be fine with `Ordering::AcqRel` (`Relaxed` on failure), so the resetting of the `value`. `.fetch_add` would be fine with `Relaxed`. Until proven wrong 🤣 That being said, `Relaxed` is `AcqRel` on the platforms we're targeting (all strongly-ordered platforms) if I'm not mistaken.

**Comment by alexsnaps** [comment]
So... building on this, I realize that sometimes you want to decrement the counter. Eg. there are 2 counters for different durations (per second limit and one per minute), so if we evaluate the per minute first and that passes, but the per second fails, we should decrement the former...

So I came up with some logic to do that, that return the expiry of the counter that got incremented and returns the tuple back, so you can "revert" the call with `return_to`

<details>

```rust
pub struct ConcurrentCounter {
    value: AtomicU64,
    expires_at: AtomicU64,
    duration: u64,
}

impl ConcurrentCounter {
    pub fn next_at(&self, at: u64, delta: u64) -> (u64, u64) {
        let mut expiry = self.expires_at.load(Ordering::Acquire);
        if at >= expiry {
            let cas = self
                .expires_at
                .compare_exchange(
                    expiry,
                    at + self.duration,
                    Ordering::Release,
                    Ordering::Relaxed,
                );
            if cas.is_ok() {
                self.value.store(delta, Ordering::Release);
                return (delta, cas.ok().unwrap());
            } else {
                expiry = cas.err().unwrap();
            }
        }
        (self.value.fetch_add(delta, Ordering::Relaxed) + delta, expiry)
    }
    
    pub fn return_to(&self, at: u64, delta: u64) -> bool {
        let nuclear = Ordering::SeqCst;
        // are we still in time to return?
        while at == self.expires_at.load(nuclear) {
            // we are, load the value
            let current = self.value.load(nuclear);
            // can we even subtract that value without rolling over?
            if current > delta {
                // ok, let's try
                if self.value.compare_exchange(current, current - delta, nuclear, nuclear).is_ok() {
                    return true;
                }
                // otherwise... spin. Tho this could spin until the counter expires! 
                // might want to just tableflip after a few tries
            } else {
                return false;
            }
        }
        false
    }
}
```

</details>

I _think_ if we order the counters by observed expiry _before_ we increment them tho, we can actually ignore giving the delta back. As the counter that was incremented, will expire (and as such be rest) before the counter that tripped. That being said, by the time we increment the counter, it might have been reset (by some other thread) _and might_ now expire after the counter that tripped. All that to say that some logic on the callsite can decide to _not_ `return_to` if the expiry returned at `next_at` invoke is earlier than the one of the counter that tripped at `next_at` as well.

**Comment by andrewdavidmackenzie** [comment]
Seems the concern about counting down (undoing an increment) is related to the first "hit" that crosses a threshold and gets limited, so ensuring that the count never exceed the limit and as it is being denied that it doesn't count against other limits on other time periods, right?

Maybe Egus can confirm how apisonator does it, but I think it might be a transaction on a set of counters (one for each time granularity) if they are all within limits, if not they will all be left as they are?

**Comment by andrewdavidmackenzie** [comment]
A related question is the granularity of locks for atomic counting. IMO this might be a tricky one to get "perfect" requiring load tests with specific profiles of traffic stressing many threads, as contention on the locks is what will slow some of them down. 

if there is a lock on every counter, and each hit requires incrementing many of them (one for each time period at least? so maybe 7 or more) there will be a lot more unlocking being done that the global one (one per hit?), but much higher parallelism possible if all hits not all hitting the same counters.... so depends on total load, number of cores, number of threads and traffic profile (all same methods, paths and limit being hit, or spread out?) that leads to the level of contention for a given atomic counter.

There maybe optimal "compromise" solutions, with a lock per REST operation that causes updates to a number of different counters.

I think a bench mark (a rust bench, but maybe also a system level benchmark) to know you are actually improving things would be required.....

**Comment by andrewdavidmackenzie** [comment]
A more radical solution (that I can't resist commenting) is about the level of consistency we guarantee in the counters and hence the precision of the limits (e.g. in apisonator we have multiple workers in background with eventual consistency and limits can be exceeded by a small amount in some cases before they are updated...vs. 100% precision in enforcing limits via atomic updates).... 

If consistency (and hence limit accuracy) could be relaxed you could avoid atomicity altogether and use other methods, including CRDTs that can combine the results of counter modifications happening in parallel.

**Comment by alexsnaps** [comment]
>if there is a lock on every counter, and each hit requires incrementing many of them (one for each time period at least? so maybe 7 or more) there will be a lot more unlocking being done that the global one (one per hit?), but much higher parallelism possible if all hits not all hitting the same counters....

@andrewdavidmackenzie  Are you meaning to say "as compared to today's single lock"? Yes, there is more locking/unlocking going on indeed. but with the proposal above mostly only read locks right? So that's "yet another counter increment", i.e. there is no serializations, these "read" (that do increment the counter) are all in parallel. Only when the expiry hits, some coordination being required because of this whole "giving the increment back"-business _and_ not exposing weird expiry/value pairs. That latter part tho, I think we might be able to get rid of in the "client code" (i.e. not in the counter itself, but in the `Limit` that checks whether `counter.next() > self.threshold`). If that's the case then I think we can support "consistency" fairly well… tho there still might be some "races" around limit overlapping not perfectly and counters expiry. But I _think_ no one could ever "prove" those from the outside. What I mean by this, is it would be impossible for someone to actually prove this request wasn't limited because of the "per minute counter" not having yet reset, while underneath it did, but you hit an overlapping "per second" limit.

>If consistency (and hence limit accuracy) could be relaxed you could avoid atomicity altogether and use other methods, including CRDTs that can combine the results of counter modifications happening in parallel.

If the previous section turns out to be not entirely wrong, then I think "only paying the price" of eventual consistency when distributed across process is possibly "nicer"? But yeah, having CRDTs that are replicated per thread (whether on a single machine or across the globe) would be another way… and merely changes how eventual things are. I just don't know how the domain is applicable to this all.

**Comment by andrewdavidmackenzie** [comment]
I'd need to study the code, and not sure how "sets" of counters (across different time periods) are organized or gathered into sets for incrementing...but here's some rambling thoughts... (this is probably all "premature optimization" BTW).

Wouldn't the optimal be to have a lock on the set of counters associated with a particular operation, say the 8 counters that need to be incremented when a hit matches that operation) (say: second, minute, hour, day, week, month, year, eternity)?

That would be the minimum number of locks/unlocks per hit (1) but allow parallel lock/unlock across operations and hence be better than 1 global lock.

It would require something like:
- a set of counters per operation/limit defined
- constantly resetting the counters to 0 when they expire.
- locking the set to increment them all, unlock without write if overlimits, write and unlock if within limits
e.g. each second the second counter resets to 0. 
A "reset timer" every second? Maybe the reset operation could be done without a lock (atomic write of 0 in one machine word)?

**Comment by alexsnaps** [comment]
>In the limit, you could have two requests that both read the counters within limits (-1), and decide to go ahead and increment...one gets a lock the other blocks on it, then first writes and unlocks, then second gets lock and writes?

@andrewdavidmackenzie no, this isn't a read-modify-store issue. The counters use atomic operations. Leaving aside how that's implemented on different architecture… Now it does become a read-modify-store issue on returning the value. While we can make it so the counter remains consistent at all time, there is a chance for someone to use the incremented value _before_ it was returned indeed. Now we're talking at worst one second before it expires and how that interact with other counters, well is up for definition… which leads to the next part:

>Wouldn't the optimal be to have a lock on the set of counters associated with a particular operation, say the 8 counters that need to be incremented when a hit matches that operation) (say: second, minute, hour, day, week, month, year, eternity)?

Yes… that's optimal indeed. There a few things that we could infer from that. If we say that a minute counter always perfectly aligns with the equivalent per second counter, then we don't ever need to give the value back to a monotonically incrementing counter. But does not need to be the case sadly...

So ideally we'd synchronize access around the set of limits _applicable_ to a request… now I think that becomes hard to know (eventually impossible maybe even, P vs NP), because of the conditions _I think_. There could be complex enough cases where we can't possibly predict all sets and as such "create" the right set of `RwLock` to use. Now there would not need to perfect… just complete. And so that there is never a request using some unrelated Lock while another do. Tho even there again, if all is implemented to be thread safe irrespectively of the lock, but the lock "only" enabling the coordination _when "returning" a value to the counter_ we *might* be good?!

**Comment by alexsnaps** [comment]
See #37

**Comment by alexsnaps** [comment]
Marking as closed, as bunch of that work happened... and while we can probably take this a lot lot further, I think we can safely park that work for now and come back with something more concrete later
